TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt
TARGET = talker

#DEPENDPATH:应用程序所依赖的搜索路径
INCLUDEPATH += \
    $$PWD/../../include/ \
    $$PWD/../../lib/ \
    $$/usr/local/include/boost/

DEPENDPATH += \
    $$PWD/../../src/ \
    $$PWD/../../lib/ \
    $$PWD/usr/local/lib/

#-L添加目录，-l指定共享库名称
unix:!macx: LIBS += \
    -lpthread \
   #-L$$PWD/../lib/ -lrosbag \
    -L$$PWD/../../lib/ -lactionlib \
    -L$$PWD/../../lib/ -lbondcpp \
    -L$$PWD/../../lib/ -lclass_loader \
    -L$$PWD/../../lib/ -lcpp_common \
    -L$$PWD/../../lib/ -ldynamic_reconfigure_config_init_mutex \
    -L$$PWD/../../lib/ -lmessage_filters \
    -L$$PWD/../../lib/ -lnodeletlib \
    -L$$PWD/../../lib/ -lrosbag_storage \
    -L$$PWD/../../lib/ -lrosconsole \
    -L$$PWD/../../lib/ -lrosconsole_backend_interface \
    -L$$PWD/../../lib/ -lrosconsole_log4cxx \
    -L$$PWD/../../lib/ -lrosconsole_bridge \
    -L$$PWD/../../lib/ -lroscpp_serialization \
    -L$$PWD/../../lib/ -lroslib \
    -L$$PWD/../../lib/ -lroslz4 \
    -L$$PWD/../../lib/ -lrospack \
    -L$$PWD/../../lib/ -lrostime \
    -L$$PWD/../../lib/ -ltopic_tools \
    -L$$PWD/../../lib/ -lxmlrpcpp \
    -L$$/usr/local/lib/ -lboost_signals \
    -L$$/usr/local/lib/ -lboost_system \
    -L$$/usr/local/lib/ -lboost_regex \
    -L$$/usr/local/lib/ -lboost_date_time \
    -L$$/usr/local/lib/ -lboost_thread \
    -L$$/usr/local/lib/ -lboost_filesystem \
    -L$$/usr/local/lib/ -lboost_thread \
    -L$$/usr/local/lib/ -lboost_regex \
    -L$$/usr/local/lib/ -lboost_chrono

HEADERS += \
    ../../include/actionlib/TestAction.h \
    ../../include/actionlib/TestActionFeedback.h \
    ../../include/actionlib/TestActionGoal.h \
    ../../include/actionlib/TestActionResult.h \
    ../../include/actionlib/TestFeedback.h \
    ../../include/actionlib/TestGoal.h \
    ../../include/actionlib/TestRequestAction.h \
    ../../include/actionlib/TestRequestActionFeedback.h \
    ../../include/actionlib/TestRequestActionGoal.h \
    ../../include/actionlib/TestRequestActionResult.h \
    ../../include/actionlib/TestRequestFeedback.h \
    ../../include/actionlib/TestRequestGoal.h \
    ../../include/actionlib/TestRequestResult.h \
    ../../include/actionlib/TestResult.h \
    ../../include/actionlib/TwoIntsAction.h \
    ../../include/actionlib/TwoIntsActionFeedback.h \
    ../../include/actionlib/TwoIntsActionGoal.h \
    ../../include/actionlib/TwoIntsActionResult.h \
    ../../include/actionlib/TwoIntsFeedback.h \
    ../../include/actionlib/TwoIntsGoal.h \
    ../../include/actionlib/TwoIntsResult.h \
    ../../include/actionlib/action_definition.h \
    ../../include/actionlib/client/action_client.h \
    ../../include/actionlib/client/client_goal_handle_imp.h \
    ../../include/actionlib/client/client_helpers.h \
    ../../include/actionlib/client/comm_state.h \
    ../../include/actionlib/client/comm_state_machine_imp.h \
    ../../include/actionlib/client/connection_monitor.h \
    ../../include/actionlib/client/goal_manager_imp.h \
    ../../include/actionlib/client/service_client.h \
    ../../include/actionlib/client/service_client_imp.h \
    ../../include/actionlib/client/simple_action_client.h \
    ../../include/actionlib/client/simple_client_goal_state.h \
    ../../include/actionlib/client/simple_goal_state.h \
    ../../include/actionlib/client/terminal_state.h \
    ../../include/actionlib/client_goal_status.h \
    ../../include/actionlib/decl.h \
    ../../include/actionlib/destruction_guard.h \
    ../../include/actionlib/enclosure_deleter.h \
    ../../include/actionlib/goal_id_generator.h \
    ../../include/actionlib/managed_list.h \
    ../../include/actionlib/one_shot_timer.h \
    ../../include/actionlib/server/action_server.h \
    ../../include/actionlib/server/action_server_base.h \
    ../../include/actionlib/server/action_server_imp.h \
    ../../include/actionlib/server/handle_tracker_deleter.h \
    ../../include/actionlib/server/handle_tracker_deleter_imp.h \
    ../../include/actionlib/server/server_goal_handle.h \
    ../../include/actionlib/server/server_goal_handle_imp.h \
    ../../include/actionlib/server/service_server.h \
    ../../include/actionlib/server/service_server_imp.h \
    ../../include/actionlib/server/simple_action_server.h \
    ../../include/actionlib/server/simple_action_server_imp.h \
    ../../include/actionlib/server/status_tracker.h \
    ../../include/actionlib/server/status_tracker_imp.h \
    ../../include/actionlib_msgs/GoalID.h \
    ../../include/actionlib_msgs/GoalStatus.h \
    ../../include/actionlib_msgs/GoalStatusArray.h \
    ../../include/bond/Constants.h \
    ../../include/bond/Status.h \
    ../../include/bondcpp/BondSM_sm.h \
    ../../include/bondcpp/bond.h \
    ../../include/bondcpp/timeout.h \
    ../../include/boost_161_condition_variable.h \
    ../../include/boost_161_pthread_condition_variable.h \
    ../../include/boost_161_pthread_condition_variable_fwd.h \
    ../../include/class_loader/class_loader.h \
    ../../include/class_loader/class_loader.hpp \
    ../../include/class_loader/class_loader_core.h \
    ../../include/class_loader/class_loader_core.hpp \
    ../../include/class_loader/class_loader_exceptions.h \
    ../../include/class_loader/class_loader_register_macro.h \
    ../../include/class_loader/console_bridge_compatibility.h \
    ../../include/class_loader/console_bridge_compatibility.hpp \
    ../../include/class_loader/exceptions.hpp \
    ../../include/class_loader/meta_object.h \
    ../../include/class_loader/meta_object.hpp \
    ../../include/class_loader/multi_library_class_loader.h \
    ../../include/class_loader/multi_library_class_loader.hpp \
    ../../include/class_loader/register_macro.hpp \
    ../../include/diagnostic_msgs/AddDiagnostics.h \
    ../../include/diagnostic_msgs/AddDiagnosticsRequest.h \
    ../../include/diagnostic_msgs/AddDiagnosticsResponse.h \
    ../../include/diagnostic_msgs/DiagnosticArray.h \
    ../../include/diagnostic_msgs/DiagnosticStatus.h \
    ../../include/diagnostic_msgs/KeyValue.h \
    ../../include/diagnostic_msgs/SelfTest.h \
    ../../include/diagnostic_msgs/SelfTestRequest.h \
    ../../include/diagnostic_msgs/SelfTestResponse.h \
    ../../include/dynamic_reconfigure/BoolParameter.h \
    ../../include/dynamic_reconfigure/Config.h \
    ../../include/dynamic_reconfigure/ConfigDescription.h \
    ../../include/dynamic_reconfigure/DoubleParameter.h \
    ../../include/dynamic_reconfigure/Group.h \
    ../../include/dynamic_reconfigure/GroupState.h \
    ../../include/dynamic_reconfigure/IntParameter.h \
    ../../include/dynamic_reconfigure/ParamDescription.h \
    ../../include/dynamic_reconfigure/Reconfigure.h \
    ../../include/dynamic_reconfigure/ReconfigureRequest.h \
    ../../include/dynamic_reconfigure/ReconfigureResponse.h \
    ../../include/dynamic_reconfigure/SensorLevels.h \
    ../../include/dynamic_reconfigure/StrParameter.h \
    ../../include/dynamic_reconfigure/TestConfig.h \
    ../../include/dynamic_reconfigure/client.h \
    ../../include/dynamic_reconfigure/config_init_mutex.h \
    ../../include/dynamic_reconfigure/config_tools.h \
    ../../include/dynamic_reconfigure/server.h \
    ../../include/geometry_msgs/Accel.h \
    ../../include/geometry_msgs/AccelStamped.h \
    ../../include/geometry_msgs/AccelWithCovariance.h \
    ../../include/geometry_msgs/AccelWithCovarianceStamped.h \
    ../../include/geometry_msgs/Inertia.h \
    ../../include/geometry_msgs/InertiaStamped.h \
    ../../include/geometry_msgs/Point.h \
    ../../include/geometry_msgs/Point32.h \
    ../../include/geometry_msgs/PointStamped.h \
    ../../include/geometry_msgs/Polygon.h \
    ../../include/geometry_msgs/PolygonStamped.h \
    ../../include/geometry_msgs/Pose.h \
    ../../include/geometry_msgs/Pose2D.h \
    ../../include/geometry_msgs/PoseArray.h \
    ../../include/geometry_msgs/PoseStamped.h \
    ../../include/geometry_msgs/PoseWithCovariance.h \
    ../../include/geometry_msgs/PoseWithCovarianceStamped.h \
    ../../include/geometry_msgs/Quaternion.h \
    ../../include/geometry_msgs/QuaternionStamped.h \
    ../../include/geometry_msgs/Transform.h \
    ../../include/geometry_msgs/TransformStamped.h \
    ../../include/geometry_msgs/Twist.h \
    ../../include/geometry_msgs/TwistStamped.h \
    ../../include/geometry_msgs/TwistWithCovariance.h \
    ../../include/geometry_msgs/TwistWithCovarianceStamped.h \
    ../../include/geometry_msgs/Vector3.h \
    ../../include/geometry_msgs/Vector3Stamped.h \
    ../../include/geometry_msgs/Wrench.h \
    ../../include/geometry_msgs/WrenchStamped.h \
    ../../include/message_filters/cache.h \
    ../../include/message_filters/chain.h \
    ../../include/message_filters/connection.h \
    ../../include/message_filters/macros.h \
    ../../include/message_filters/null_types.h \
    ../../include/message_filters/pass_through.h \
    ../../include/message_filters/signal1.h \
    ../../include/message_filters/signal9.h \
    ../../include/message_filters/simple_filter.h \
    ../../include/message_filters/subscriber.h \
    ../../include/message_filters/sync_policies/approximate_time.h \
    ../../include/message_filters/sync_policies/exact_time.h \
    ../../include/message_filters/synchronizer.h \
    ../../include/message_filters/time_sequencer.h \
    ../../include/message_filters/time_synchronizer.h \
    ../../include/nav_msgs/GetMap.h \
    ../../include/nav_msgs/GetMapAction.h \
    ../../include/nav_msgs/GetMapActionFeedback.h \
    ../../include/nav_msgs/GetMapActionGoal.h \
    ../../include/nav_msgs/GetMapActionResult.h \
    ../../include/nav_msgs/GetMapFeedback.h \
    ../../include/nav_msgs/GetMapGoal.h \
    ../../include/nav_msgs/GetMapRequest.h \
    ../../include/nav_msgs/GetMapResponse.h \
    ../../include/nav_msgs/GetMapResult.h \
    ../../include/nav_msgs/GetPlan.h \
    ../../include/nav_msgs/GetPlanRequest.h \
    ../../include/nav_msgs/GetPlanResponse.h \
    ../../include/nav_msgs/GridCells.h \
    ../../include/nav_msgs/MapMetaData.h \
    ../../include/nav_msgs/OccupancyGrid.h \
    ../../include/nav_msgs/Odometry.h \
    ../../include/nav_msgs/Path.h \
    ../../include/nav_msgs/SetMap.h \
    ../../include/nav_msgs/SetMapRequest.h \
    ../../include/nav_msgs/SetMapResponse.h \
    ../../include/nodelet/NodeletList.h \
    ../../include/nodelet/NodeletListRequest.h \
    ../../include/nodelet/NodeletListResponse.h \
    ../../include/nodelet/NodeletLoad.h \
    ../../include/nodelet/NodeletLoadRequest.h \
    ../../include/nodelet/NodeletLoadResponse.h \
    ../../include/nodelet/NodeletUnload.h \
    ../../include/nodelet/NodeletUnloadRequest.h \
    ../../include/nodelet/NodeletUnloadResponse.h \
    ../../include/nodelet/detail/callback_queue.h \
    ../../include/nodelet/detail/callback_queue_manager.h \
    ../../include/nodelet/exception.h \
    ../../include/nodelet/loader.h \
    ../../include/nodelet/nodelet.h \
    ../../include/nodelet_topic_tools/NodeletThrottleConfig.h \
    ../../include/nodelet_topic_tools/nodelet_demux.h \
    ../../include/nodelet_topic_tools/nodelet_lazy.h \
    ../../include/nodelet_topic_tools/nodelet_mux.h \
    ../../include/nodelet_topic_tools/nodelet_throttle.h \
    ../../include/pluginlib/class_desc.h \
    ../../include/pluginlib/class_desc.hpp \
    ../../include/pluginlib/class_list_macros.h \
    ../../include/pluginlib/class_list_macros.hpp \
    ../../include/pluginlib/class_loader.h \
    ../../include/pluginlib/class_loader.hpp \
    ../../include/pluginlib/class_loader_base.h \
    ../../include/pluginlib/class_loader_base.hpp \
    ../../include/pluginlib/class_loader_imp.h \
    ../../include/pluginlib/class_loader_imp.hpp \
    ../../include/pluginlib/exceptions.hpp \
    ../../include/pluginlib/pluginlib_exceptions.h \
    ../../include/ros/advertise_options.h \
    ../../include/ros/advertise_service_options.h \
    ../../include/ros/assert.h \
    ../../include/ros/builtin_message_traits.h \
    ../../include/ros/callback_queue.h \
    ../../include/ros/callback_queue_interface.h \
    ../../include/ros/common.h \
    ../../include/ros/connection.h \
    ../../include/ros/connection_manager.h \
    ../../include/ros/console.h \
    ../../include/ros/console_backend.h \
    ../../include/ros/cpp_common_decl.h \
    ../../include/ros/datatypes.h \
    ../../include/ros/debug.h \
    ../../include/ros/duration.h \
    ../../include/ros/exception.h \
    ../../include/ros/exceptions.h \
    ../../include/ros/file_log.h \
    ../../include/ros/forwards.h \
    ../../include/ros/header.h \
    ../../include/ros/impl/duration.h \
    ../../include/ros/impl/time.h \
    ../../include/ros/init.h \
    ../../include/ros/internal_timer_manager.h \
    ../../include/ros/intraprocess_publisher_link.h \
    ../../include/ros/intraprocess_subscriber_link.h \
    ../../include/ros/io.h \
    ../../include/ros/macros.h \
    ../../include/ros/master.h \
    ../../include/ros/message.h \
    ../../include/ros/message_deserializer.h \
    ../../include/ros/message_event.h \
    ../../include/ros/message_forward.h \
    ../../include/ros/message_operations.h \
    ../../include/ros/message_traits.h \
    ../../include/ros/names.h \
    ../../include/ros/network.h \
    ../../include/ros/node_handle.h \
    ../../include/ros/package.h \
    ../../include/ros/param.h \
    ../../include/ros/parameter_adapter.h \
    ../../include/ros/platform.h \
    ../../include/ros/poll_manager.h \
    ../../include/ros/poll_set.h \
    ../../include/ros/publication.h \
    ../../include/ros/publisher.h \
    ../../include/ros/publisher_link.h \
    ../../include/ros/rate.h \
    ../../include/ros/ros.h \
    ../../include/ros/roscpp_serialization_macros.h \
    ../../include/ros/rosout_appender.h \
    ../../include/ros/rostime_decl.h \
    ../../include/ros/serialization.h \
    ../../include/ros/serialized_message.h \
    ../../include/ros/service.h \
    ../../include/ros/service_callback_helper.h \
    ../../include/ros/service_client.h \
    ../../include/ros/service_client_link.h \
    ../../include/ros/service_client_options.h \
    ../../include/ros/service_manager.h \
    ../../include/ros/service_publication.h \
    ../../include/ros/service_server.h \
    ../../include/ros/service_server_link.h \
    ../../include/ros/service_traits.h \
    ../../include/ros/single_subscriber_publisher.h \
    ../../include/ros/spinner.h \
    ../../include/ros/static_assert.h \
    ../../include/ros/statistics.h \
    ../../include/ros/steady_timer.h \
    ../../include/ros/steady_timer_options.h \
    ../../include/ros/subscribe_options.h \
    ../../include/ros/subscriber.h \
    ../../include/ros/subscriber_link.h \
    ../../include/ros/subscription.h \
    ../../include/ros/subscription_callback_helper.h \
    ../../include/ros/subscription_queue.h \
    ../../include/ros/this_node.h \
    ../../include/ros/time.h \
    ../../include/ros/timer.h \
    ../../include/ros/timer_manager.h \
    ../../include/ros/timer_options.h \
    ../../include/ros/topic.h \
    ../../include/ros/topic_manager.h \
    ../../include/ros/transport/transport.h \
    ../../include/ros/transport/transport_tcp.h \
    ../../include/ros/transport/transport_udp.h \
    ../../include/ros/transport_hints.h \
    ../../include/ros/transport_publisher_link.h \
    ../../include/ros/transport_subscriber_link.h \
    ../../include/ros/types.h \
    ../../include/ros/wall_timer.h \
    ../../include/ros/wall_timer_options.h \
    ../../include/ros/xmlrpc_manager.h \
    ../../include/rosbag/bag.h \
    ../../include/rosbag/bag_player.h \
    ../../include/rosbag/buffer.h \
    ../../include/rosbag/chunked_file.h \
    ../../include/rosbag/console_bridge_compatibility.h \
    ../../include/rosbag/constants.h \
    ../../include/rosbag/exceptions.h \
    ../../include/rosbag/macros.h \
    ../../include/rosbag/message_instance.h \
    ../../include/rosbag/player.h \
    ../../include/rosbag/query.h \
    ../../include/rosbag/recorder.h \
    ../../include/rosbag/stream.h \
    ../../include/rosbag/structures.h \
    ../../include/rosbag/time_translator.h \
    ../../include/rosbag/view.h \
    ../../include/rosconsole/macros_generated.h \
    ../../include/rosconsole_bridge/bridge.h \
    ../../include/roscpp/Empty.h \
    ../../include/roscpp/EmptyRequest.h \
    ../../include/roscpp/EmptyResponse.h \
    ../../include/roscpp/GetLoggers.h \
    ../../include/roscpp/GetLoggersRequest.h \
    ../../include/roscpp/GetLoggersResponse.h \
    ../../include/roscpp/Logger.h \
    ../../include/roscpp/SetLoggerLevel.h \
    ../../include/roscpp/SetLoggerLevelRequest.h \
    ../../include/roscpp/SetLoggerLevelResponse.h \
    ../../include/rosgraph_msgs/Clock.h \
    ../../include/rosgraph_msgs/Log.h \
    ../../include/rosgraph_msgs/TopicStatistics.h \
    ../../include/roslz4/lz4s.h \
    ../../include/rospack/macros.h \
    ../../include/rospack/rospack.h \
    ../../include/rospack/rospack_backcompat.h \
    ../../include/rostest/permuter.h \
    ../../include/sensor_msgs/BatteryState.h \
    ../../include/sensor_msgs/CameraInfo.h \
    ../../include/sensor_msgs/ChannelFloat32.h \
    ../../include/sensor_msgs/CompressedImage.h \
    ../../include/sensor_msgs/FluidPressure.h \
    ../../include/sensor_msgs/Illuminance.h \
    ../../include/sensor_msgs/Image.h \
    ../../include/sensor_msgs/Imu.h \
    ../../include/sensor_msgs/JointState.h \
    ../../include/sensor_msgs/Joy.h \
    ../../include/sensor_msgs/JoyFeedback.h \
    ../../include/sensor_msgs/JoyFeedbackArray.h \
    ../../include/sensor_msgs/LaserEcho.h \
    ../../include/sensor_msgs/LaserScan.h \
    ../../include/sensor_msgs/MagneticField.h \
    ../../include/sensor_msgs/MultiDOFJointState.h \
    ../../include/sensor_msgs/MultiEchoLaserScan.h \
    ../../include/sensor_msgs/NavSatFix.h \
    ../../include/sensor_msgs/NavSatStatus.h \
    ../../include/sensor_msgs/PointCloud.h \
    ../../include/sensor_msgs/PointCloud2.h \
    ../../include/sensor_msgs/PointField.h \
    ../../include/sensor_msgs/Range.h \
    ../../include/sensor_msgs/RegionOfInterest.h \
    ../../include/sensor_msgs/RelativeHumidity.h \
    ../../include/sensor_msgs/SetCameraInfo.h \
    ../../include/sensor_msgs/SetCameraInfoRequest.h \
    ../../include/sensor_msgs/SetCameraInfoResponse.h \
    ../../include/sensor_msgs/Temperature.h \
    ../../include/sensor_msgs/TimeReference.h \
    ../../include/sensor_msgs/distortion_models.h \
    ../../include/sensor_msgs/fill_image.h \
    ../../include/sensor_msgs/image_encodings.h \
    ../../include/sensor_msgs/impl/point_cloud2_iterator.h \
    ../../include/sensor_msgs/point_cloud2_iterator.h \
    ../../include/sensor_msgs/point_cloud_conversion.h \
    ../../include/sensor_msgs/point_field_conversion.h \
    ../../include/shape_msgs/Mesh.h \
    ../../include/shape_msgs/MeshTriangle.h \
    ../../include/shape_msgs/Plane.h \
    ../../include/shape_msgs/SolidPrimitive.h \
    ../../include/smclib/statemap.h \
    ../../include/std_msgs/Bool.h \
    ../../include/std_msgs/Byte.h \
    ../../include/std_msgs/ByteMultiArray.h \
    ../../include/std_msgs/Char.h \
    ../../include/std_msgs/ColorRGBA.h \
    ../../include/std_msgs/Duration.h \
    ../../include/std_msgs/Empty.h \
    ../../include/std_msgs/Float32.h \
    ../../include/std_msgs/Float32MultiArray.h \
    ../../include/std_msgs/Float64.h \
    ../../include/std_msgs/Float64MultiArray.h \
    ../../include/std_msgs/Header.h \
    ../../include/std_msgs/Int16.h \
    ../../include/std_msgs/Int16MultiArray.h \
    ../../include/std_msgs/Int32.h \
    ../../include/std_msgs/Int32MultiArray.h \
    ../../include/std_msgs/Int64.h \
    ../../include/std_msgs/Int64MultiArray.h \
    ../../include/std_msgs/Int8.h \
    ../../include/std_msgs/Int8MultiArray.h \
    ../../include/std_msgs/MultiArrayDimension.h \
    ../../include/std_msgs/MultiArrayLayout.h \
    ../../include/std_msgs/String.h \
    ../../include/std_msgs/Time.h \
    ../../include/std_msgs/UInt16.h \
    ../../include/std_msgs/UInt16MultiArray.h \
    ../../include/std_msgs/UInt32.h \
    ../../include/std_msgs/UInt32MultiArray.h \
    ../../include/std_msgs/UInt64.h \
    ../../include/std_msgs/UInt64MultiArray.h \
    ../../include/std_msgs/UInt8.h \
    ../../include/std_msgs/UInt8MultiArray.h \
    ../../include/std_msgs/builtin_bool.h \
    ../../include/std_msgs/builtin_double.h \
    ../../include/std_msgs/builtin_float.h \
    ../../include/std_msgs/builtin_int16.h \
    ../../include/std_msgs/builtin_int32.h \
    ../../include/std_msgs/builtin_int64.h \
    ../../include/std_msgs/builtin_int8.h \
    ../../include/std_msgs/builtin_string.h \
    ../../include/std_msgs/builtin_uint16.h \
    ../../include/std_msgs/builtin_uint32.h \
    ../../include/std_msgs/builtin_uint64.h \
    ../../include/std_msgs/builtin_uint8.h \
    ../../include/std_msgs/header_deprecated_def.h \
    ../../include/std_msgs/trait_macros.h \
    ../../include/std_srvs/Empty.h \
    ../../include/std_srvs/EmptyRequest.h \
    ../../include/std_srvs/EmptyResponse.h \
    ../../include/std_srvs/SetBool.h \
    ../../include/std_srvs/SetBoolRequest.h \
    ../../include/std_srvs/SetBoolResponse.h \
    ../../include/std_srvs/Trigger.h \
    ../../include/std_srvs/TriggerRequest.h \
    ../../include/std_srvs/TriggerResponse.h \
    ../../include/stereo_msgs/DisparityImage.h \
    ../../include/topic_tools/DemuxAdd.h \
    ../../include/topic_tools/DemuxAddRequest.h \
    ../../include/topic_tools/DemuxAddResponse.h \
    ../../include/topic_tools/DemuxDelete.h \
    ../../include/topic_tools/DemuxDeleteRequest.h \
    ../../include/topic_tools/DemuxDeleteResponse.h \
    ../../include/topic_tools/DemuxList.h \
    ../../include/topic_tools/DemuxListRequest.h \
    ../../include/topic_tools/DemuxListResponse.h \
    ../../include/topic_tools/DemuxSelect.h \
    ../../include/topic_tools/DemuxSelectRequest.h \
    ../../include/topic_tools/DemuxSelectResponse.h \
    ../../include/topic_tools/MuxAdd.h \
    ../../include/topic_tools/MuxAddRequest.h \
    ../../include/topic_tools/MuxAddResponse.h \
    ../../include/topic_tools/MuxDelete.h \
    ../../include/topic_tools/MuxDeleteRequest.h \
    ../../include/topic_tools/MuxDeleteResponse.h \
    ../../include/topic_tools/MuxList.h \
    ../../include/topic_tools/MuxListRequest.h \
    ../../include/topic_tools/MuxListResponse.h \
    ../../include/topic_tools/MuxSelect.h \
    ../../include/topic_tools/MuxSelectRequest.h \
    ../../include/topic_tools/MuxSelectResponse.h \
    ../../include/topic_tools/macros.h \
    ../../include/topic_tools/parse.h \
    ../../include/topic_tools/shape_shifter.h \
    ../../include/trajectory_msgs/JointTrajectory.h \
    ../../include/trajectory_msgs/JointTrajectoryPoint.h \
    ../../include/trajectory_msgs/MultiDOFJointTrajectory.h \
    ../../include/trajectory_msgs/MultiDOFJointTrajectoryPoint.h \
    ../../include/visualization_msgs/ImageMarker.h \
    ../../include/visualization_msgs/InteractiveMarker.h \
    ../../include/visualization_msgs/InteractiveMarkerControl.h \
    ../../include/visualization_msgs/InteractiveMarkerFeedback.h \
    ../../include/visualization_msgs/InteractiveMarkerInit.h \
    ../../include/visualization_msgs/InteractiveMarkerPose.h \
    ../../include/visualization_msgs/InteractiveMarkerUpdate.h \
    ../../include/visualization_msgs/Marker.h \
    ../../include/visualization_msgs/MarkerArray.h \
    ../../include/visualization_msgs/MenuEntry.h \
    ../../include/xmlrpcpp/XmlRpc.h \
    ../../include/xmlrpcpp/XmlRpcClient.h \
    ../../include/xmlrpcpp/XmlRpcDecl.h \
    ../../include/xmlrpcpp/XmlRpcDispatch.h \
    ../../include/xmlrpcpp/XmlRpcException.h \
    ../../include/xmlrpcpp/XmlRpcServer.h \
    ../../include/xmlrpcpp/XmlRpcServerConnection.h \
    ../../include/xmlrpcpp/XmlRpcServerMethod.h \
    ../../include/xmlrpcpp/XmlRpcSocket.h \
    ../../include/xmlrpcpp/XmlRpcSource.h \
    ../../include/xmlrpcpp/XmlRpcUtil.h \
    ../../include/xmlrpcpp/XmlRpcValue.h \
    ../../include/xmlrpcpp/base64.h \
    ../../src/config.h \

SOURCES +=  \
    talker.cpp \
    ../../src/callback_queue.cpp \
    ../../src/common.cpp \
    ../../src/connection.cpp \
    ../../src/connection_manager.cpp \
    ../../src/file_log.cpp \
    ../../src/init.cpp \
    ../../src/internal_timer_manager.cpp \
    ../../src/intraprocess_publisher_link.cpp \
    ../../src/intraprocess_subscriber_link.cpp \
    ../../src/io.cpp \
    ../../src/master.cpp \
    ../../src/message_deserializer.cpp \
    ../../src/names.cpp \
    ../../src/network.cpp \
    ../../src/node_handle.cpp \
    ../../src/param.cpp \
    ../../src/poll_manager.cpp \
    ../../src/poll_set.cpp \
    ../../src/publication.cpp \
    ../../src/publisher.cpp \
    ../../src/publisher_link.cpp \
    ../../src/rosout_appender.cpp \
    ../../src/service.cpp \
    ../../src/service_client.cpp \
    ../../src/service_client_link.cpp \
    ../../src/service_manager.cpp \
    ../../src/service_publication.cpp \
    ../../src/service_server.cpp \
    ../../src/service_server_link.cpp \
    ../../src/single_subscriber_publisher.cpp \
    ../../src/spinner.cpp \
    ../../src/statistics.cpp \
    ../../src/steady_timer.cpp \
    ../../src/subscriber.cpp \
    ../../src/subscriber_link.cpp \
    ../../src/subscription.cpp \
    ../../src/subscription_queue.cpp \
    ../../src/this_node.cpp \
    ../../src/timer.cpp \
    ../../src/topic.cpp \
    ../../src/topic_manager.cpp \
    ../../src/transport/transport.cpp \
    ../../src/transport/transport_tcp.cpp \
    ../../src/transport/transport_udp.cpp \
    ../../src/transport_publisher_link.cpp \
    ../../src/transport_subscriber_link.cpp \
    ../../src/wall_timer.cpp \
    ../../src/xmlrpc_manager.cpp

